title: Myranth
email: myranth336@gmail.com
description: Portfolio of Phil Taylor
include: ['_pages', '_projects']
baseurl: ""
url: "http://localhost:4000"
github_username: myranth
markdown: kramdown
sass:
  sass_dir: _sass
